// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyQuanLyTrangSuc.Model;

public partial class Employee
{
    public string EmployeeId { get; set; }

    public string Name { get; set; }

    public string Position { get; set; }

    public string ContactNumber { get; set; }

    public string Email { get; set; }

    public string ImagePath { get; set; }

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();
}