// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyQuanLyTrangSuc.Model;

public partial class Function
{
    public int FunctionId { get; set; }

    public string FunctionName { get; set; }

    public string ScreenToLoad { get; set; }

    public virtual ICollection<Permission> Permissions { get; set; } = new List<Permission>();
}