// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyQuanLyTrangSuc.Model;

public partial class Import
{
    public string ImportId { get; set; }

    public string SupplierId { get; set; }

    public string EmployeeId { get; set; }

    public DateTime Date { get; set; }

    public decimal? TotalAmount { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<ImportDetail> ImportDetails { get; set; } = new List<ImportDetail>();

    public virtual Supplier Supplier { get; set; }
}