// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace MyQuanLyTrangSuc.Model;

public partial class ImportDetail: INotifyPropertyChanged
{
    public int Stt { get; set; }

    public string ImportId { get; set; }

    public string ProductId { get; set; }

    private int? _quantity;

    public int? Quantity
    {
        get => _quantity;
        set
        {
            if (_quantity != value)
            {
                _quantity = value;
                OnPropertyChanged();
                CalculateTotalPrice();
            }
        }
    }

    private decimal? _price;

    public decimal? Price
    {
        get => _price;
        set
        {
            if (_price != value)
            {
                _price = value;
                OnPropertyChanged();
                CalculateTotalPrice(); 
            }
        }
    }

    private decimal? _totalPrice;

    public decimal? TotalPrice
    {
        get => _totalPrice;
        set
        {
            if (_totalPrice != value)
            {
                _totalPrice = value;
                OnPropertyChanged(); 
            }
        }
    }

    private void CalculateTotalPrice()
    {
        TotalPrice = Quantity * Price; 
    }

    public virtual Import Import { get; set; }

    public virtual Product Product { get; set; }

    public event PropertyChangedEventHandler PropertyChanged;
    protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}