// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyQuanLyTrangSuc.Model;

public partial class InvoiceDetail
{
    public int Stt { get; set; }

    public string InvoiceId { get; set; }

    public string ProductId { get; set; }

    public int? Quantity { get; set; }

    public decimal? Price { get; set; }

    public decimal? TotalPrice { get; set; }

    public virtual Invoice Invoice { get; set; }

    public virtual Product Product { get; set; }
}