// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyQuanLyTrangSuc.Model;

public partial class Invoice
{
    public string InvoiceId { get; set; }

    public string CustomerId { get; set; }

    public DateTime? Date { get; set; }

    public decimal? TotalAmount { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; } = new List<InvoiceDetail>();
}