// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace MyQuanLyTrangSuc.Model;

public partial class InvoiceDetail : INotifyPropertyChanged
{
    public int Stt { get; set; }

    public string InvoiceId { get; set; }

    public string ProductId { get; set; }

    private int? _quantity;

    public int? Quantity
    {
        get => _quantity;
        set
        {
            if (_quantity != value)
            {
                if (value <= 0)
                {
                    value = 1;
                }
                else if (Product != null && value > Product.Quantity + _quantity)
                {
                    value = Product.Quantity + _quantity;
                }
                _quantity = value;
                OnPropertyChanged();
                CalculateTotalPrice();
            }
        }
    }

    private decimal? _price;
    public decimal? Price
    {
        get => _price;
        set
        {
            if (_price != value)
            {
                _price = value;
                OnPropertyChanged();
                CalculateTotalPrice();
            }

        }
    }

    private decimal? _totalPrice;
    public decimal? TotalPrice
    {
        get => _totalPrice;
        set
        {
            if (_totalPrice != value)
            {
                _totalPrice = value;
                OnPropertyChanged();
            }
        }
    }

    private void CalculateTotalPrice()
    {
        TotalPrice = Quantity * Price;
    }

    public virtual Invoice Invoice { get; set; }

    public virtual Product Product { get; set; }

    public event PropertyChangedEventHandler PropertyChanged;
    protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}