// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyQuanLyTrangSuc.Model;

public partial class Parameter
{
    public string ConstName { get; set; }

    public decimal? ConstValue { get; set; }
}