// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyQuanLyTrangSuc.Model;

public partial class Permission
{
    public int PermissionId { get; set; }

    public int GroupId { get; set; }

    public int FunctionId { get; set; }

    public bool IsDeleted { get; set; }

    public virtual Function Function { get; set; }

    public virtual UserGroup Group { get; set; }
}