// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyQuanLyTrangSuc.Model;

public partial class RevenueReportServiceDetail
{
    public string RevenueReportId { get; set; }

    public string ServiceId { get; set; }

    public int? Quantity { get; set; }

    public decimal? Revenue { get; set; }

    public decimal? Percentage { get; set; }

    public virtual RevenueReport RevenueReport { get; set; }

    public virtual Service Service { get; set; }
}