// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyQuanLyTrangSuc.Model;

public partial class ServiceRecord
{
    public string ServiceRecordId { get; set; }

    public DateTime? CreateDate { get; set; }

    public string CustomerId { get; set; }

    public string EmployeeId { get; set; }

    public string ImagePath { get; set; }

    public decimal? Total { get; set; }
    
    public decimal? Prepaid { get; set; }
    
    public decimal? Remain { get; set; }
   
    public string Status { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<ServiceDetail> ServiceDetails { get; set; } = new List<ServiceDetail>();
}