// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyQuanLyTrangSuc.Model;

public partial class ServiceDetail
{
    public int Stt { get; set; }

    public string ServiceRecordId { get; set; }

    public string ServiceId { get; set; }

    public int? Quantity { get; set; }

    public decimal? ExtraExpense { get; set; }

    public decimal? Prepaid { get; set; }

    public decimal? Unpaid { get; set; }

    public DateTime? DueDay { get; set; }

    public string Status { get; set; }

    public virtual Service Service { get; set; }

    public virtual ServiceRecord ServiceRecord { get; set; }
}