// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyQuanLyTrangSuc.Model;

public partial class Service
{
    public string ServiceId { get; set; }

    public string ServiceName { get; set; }

    public decimal? ServicePrice { get; set; }

    public string MoreInfo { get; set; }

    public string ImagePath { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<ServiceDetail> ServiceDetails { get; set; } = new List<ServiceDetail>();
}