// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyQuanLyTrangSuc.Model;

public partial class StockReportDetail
{
    public string StockReportId { get; set; }

    public string ProductId { get; set; }

    public int? BeginStock { get; set; }

    public int? FinishStock { get; set; }

    public int? ImportQuantity { get; set; }

    public int? SaleQuantity { get; set; }

    public virtual Product Product { get; set; }

    public virtual StockReport StockReport { get; set; }
}