// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyQuanLyTrangSuc.Model;

public partial class StockReport
{
    public DateTime MonthYear { get; set; }

    public string ProductId { get; set; }

    public int? BeginStock { get; set; }

    public int? PurchaseQuantity { get; set; }

    public int? SalesQuantity { get; set; }

    public int? FinishStock { get; set; }

    public virtual Product Product { get; set; }
}