// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyQuanLyTrangSuc.Model;

public partial class Supplier
{
    public string SupplierId { get; set; }

    public string Name { get; set; }

    public string ContactNumber { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<Import> Imports { get; set; } = new List<Import>();
}